version: '3'
services:
    nexus:
        build:
            dockerfile: Nexus3.Dockerfile
            context: ./docker-composer
        volumes:
            - "./docker/nexus-data:/opt/sonatype/sonatype-work"
        ports:
            - "8081:8081"
            - "9000:9000"
            - "9001:9001"
            - "9010:9010"
            - "9011:9011"
            - "9020:9020"
            - "9021:9021"
            - "9030:9030"
            - "9031:9031"
            

