---
- include: call_script.yml
  vars:
    script_name: update_admin_password
    args:
      new_password: "{{ nexus_admin_password }}"

- name: Admin password changed
  set_fact:
    nexus_admin_password: "{{ nexus_admin_password }}"
  no_log: true