---

- include: declare_script_each.yml
  with_items:
    - update_admin_password
    - setup_ldap
    - setup_anonymous_access
    - setup_base_url
    - setup_capability
    - setup_http_proxy
    - setup_role
    - setup_privilege
    - setup_user
    - delete_repo
    - delete_blobstore
    - create_blobstore
    - create_repo_composer_hosted
    - create_repo_composer_proxy
    - create_repo_composer_group
    - create_repo_nuget_hosted
    - create_repo_nuget_proxy
    - create_repo_nuget_group
    - create_repo_maven_proxy
    - create_repo_maven_group
    - create_repo_maven_hosted
    - create_repo_docker_hosted
    - create_repo_docker_proxy
    - create_repo_docker_group
    - create_repo_pypi_hosted
    - create_repo_pypi_proxy
    - create_repo_pypi_group
    - create_repo_raw_hosted
    - create_repo_raw_proxy
    - create_repo_raw_group
    - create_repo_rubygems_hosted
    - create_repo_rubygems_proxy
    - create_repo_rubygems_group
    - create_repo_bower_hosted
    - create_repo_bower_proxy
    - create_repo_bower_group
    - create_repo_npm_hosted
    - create_repo_npm_proxy
    - create_repo_npm_group
    - create_repo_gitlfs_hosted
    - create_task

- include: setup_privilege_each.yml
  with_items: "{{ nexus_privileges }}"

- include: setup_role_each.yml
  with_items: "{{ nexus_roles }}"

- include: setup_user_each.yml
  with_items: "{{ nexus_local_users }}"

- name: "Digest splited blob list var"
  include_vars: blob_vars.yml
  when: nexus_blob_split

- include: create_blobstore_each.yml
  with_items: "{{ nexus_blobstores }}"
  when: nexus_restore_point is undefined

#- name: "Restore nexus backup"
#  include: nexus-restore.yml
#  when: nexus_restore_point is defined


- include: create_repo_maven_proxy_each.yml
  with_items: "{{ nexus_repos_maven_proxy }}"

- include: create_repo_maven_hosted_each.yml
  with_items: "{{ nexus_repos_maven_hosted }}"

- include: create_repo_maven_group_each.yml
  with_items: "{{ nexus_repos_maven_group }}"

- block:
    - include: create_repo_composer_hosted_each.yml
      with_items: "{{ nexus_repos_composer_hosted }}"

    - include: create_repo_composer_proxy_each.yml
      with_items: "{{ nexus_repos_composer_proxy }}"

    - include: create_repo_composer_group_each.yml
      with_items: "{{ nexus_repos_composer_group }}"
  when: nexus_config_composer


- block:
    - include: create_repo_nuget_hosted_each.yml
      with_items: "{{ nexus_repos_nuget_hosted }}"

    - include: create_repo_nuget_proxy_each.yml
      with_items: "{{ nexus_repos_nuget_proxy }}"

    - include: create_repo_nuget_group_each.yml
      with_items: "{{ nexus_repos_nuget_group }}"
  when: nexus_config_nuget


- block:
  - include: create_repo_docker_hosted_each.yml
    with_items: "{{ nexus_repos_docker_hosted }}"

  - include: create_repo_docker_proxy_each.yml
    with_items: "{{ nexus_repos_docker_proxy }}"

  - include: create_repo_docker_group_each.yml
    with_items: "{{ nexus_repos_docker_group }}"
  when: nexus_config_docker


- block:
  - include: create_repo_pypi_proxy_each.yml
    with_items: "{{ nexus_repos_pypi_proxy }}"

  - include: create_repo_pypi_hosted_each.yml
    with_items: "{{ nexus_repos_pypi_hosted }}"

  - include: create_repo_pypi_group_each.yml
    with_items: "{{ nexus_repos_pypi_group }}"
  when: nexus_config_pypi

- block:
  - include: create_repo_raw_proxy_each.yml
    with_items: "{{ nexus_repos_raw_proxy }}"

  - include: create_repo_raw_hosted_each.yml
    with_items: "{{ nexus_repos_raw_hosted }}"

  - include: create_repo_raw_group_each.yml
    with_items: "{{ nexus_repos_raw_group }}"
  when: nexus_config_raw

- block:
  - include: create_repo_rubygems_proxy_each.yml
    with_items: "{{ nexus_repos_rubygems_proxy }}"

  - include: create_repo_rubygems_hosted_each.yml
    with_items: "{{ nexus_repos_rubygems_hosted }}"

  - include: create_repo_rubygems_group_each.yml
    with_items: "{{ nexus_repos_rubygems_group }}"
  when: nexus_config_rubygems

- block:
  - include: create_repo_bower_proxy_each.yml
    with_items: "{{ nexus_repos_bower_proxy }}"

  - include: create_repo_bower_hosted_each.yml
    with_items: "{{ nexus_repos_bower_hosted }}"

  - include: create_repo_bower_group_each.yml
    with_items: "{{ nexus_repos_bower_group }}"
  when: nexus_config_bower

- block:
  - include: create_repo_npm_proxy_each.yml
    with_items: "{{ nexus_repos_npm_proxy }}"

  - include: create_repo_npm_hosted_each.yml
    with_items: "{{ nexus_repos_npm_hosted }}"

  - include: create_repo_npm_group_each.yml
    with_items: "{{ nexus_repos_npm_group }}"
  when: nexus_config_npm

- include: create_repo_gitlfs_hosted_each.yml
  with_items: "{{ nexus_repos_gitlfs_hosted }}"
  when: nexus_config_gitlfs

- include: call_script.yml
  vars:
    script_name: setup_anonymous_access
    args:
      anonymous_access: "{{ nexus_anonymous_access }}"

- include: call_script.yml
  vars:
    script_name: setup_base_url
    args:
      base_url: "https://{{ public_hostname }}/"

- name: Configure branding capability
  include: call_script.yml
  vars:
    script_name: setup_capability
    args:
      capability_typeId: "rapture.branding"
      capability_properties:
        footerHtml: "{{ nexus_branding_footer }}"
        headerHtml: "{{ nexus_branding_header }}"
        footerEnabled: "{{ nexus_branding_footer != '' }}"
        headerEnabled: "{{ nexus_branding_header != '' }}"

#- include: create_task_each.yml
#  with_items: "{{ nexus_scheduled_tasks }}"
